version: '3.8'
services:
  stats-server:
    build: ./stat-server
    container_name: explore-stats
    ports:
      - "9090:9090"
    depends_on:
      - explore-stats-db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://localhost:5432/explore-stats-db

  explore-stats-db:
    image: postgres:14-alpine
    container_name: stats-db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: "explore-stats-db"
      POSTGRES_USER: "user"
      POSTGRES_PASSWORD: "user"

  ewm-service:
    build: ./main-server
    container_name: explore-main
    ports:
      - "8080:8080"
    depends_on:
      - explore-main-db
    environment:
      - STATISTIC_SERVER_URL=http://localhost:9090
      - SPRING_DATASOURCE_URL=jdbc:postgresql://localhost:5433/explore-main-db

  explore-main-db:
    image: postgres:14-alpine
    container_name: explore-server-db
    ports:
      - "5433:5433"
    environment:
      POSTGRES_DB: "explore-main-db"
      POSTGRES_USER: "user"
      POSTGRES_PASSWORD: "user"